### ISSUE TITLE
Error al darle clic en la segunda opción de convocatorias

### ISSUE THREAD

**Issue by glocalpm** [Conexion-Glocal/conexion-glocal-frontend#14]
![image](https://github.com/user-attachments/assets/b5556c42-294b-4153-a92c-7dc8b53e13ac)

**Comment by glocal-backend-leader** [comment]
Solution Applied:
Implemented a function to validate and handle the retrieved data using a conditional check.
The function ensures that only non-empty arrays are processed, avoiding potential errors when the data is null, undefined, or empty.

`Array.isArray(data) && data.length > 0
  ? data.map(({ id, name, description, body }) => {
    ...
    })
  : [];
`
